services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: potpie
    ports:
      - "5432:5432"

  celery_worker:
    build: .
    command: celery -A app.workers.celery_worker.celery_app worker --loglevel=info
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_URL=redis://redis:6379/0
      - POSTGRES_URL=postgresql://postgres:postgres@postgres:5432/potpie
    volumes:
      - .:/code
    working_dir: /code

  fastapi_app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_URL=redis://redis:6379/0
      - POSTGRES_URL=postgresql://postgres:postgres@postgres:5432/potpie
      - GROQ_API_KEY=${GROQ_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    working_dir: /code